export const cookieFlavors = [
  'chocolate-chip=YummyCookies; Path=/; HttpOnly; Secure; SameSite=Strict',
  'vanilla-bean=YummyCookies; Path=/; Max-Age=3600',
  'strawberry=YummyCookies; Path=/;',
  'mint=YummyCookies; Path=/; SameSite=Lax',
  'peanut-butter=YummyCookies; Path=/; Max-Age=86400',
  'oatmeal-raisin=YummyCookies; Path=/; HttpOnly; Secure',
  'double-chocolate=YummyCookies; Path=/; Max-Age=7200',
  'white-chocolate-macadamia=YummyCookies; Path=/; SameSite=Strict',
  'lemon-sugar=YummyCookies; Path=/;',
  'gingerbread=YummyCookies; Path=/; Max-Age=2592000',
  'snickerdoodle=YummyCookies; Path=/; HttpOnly',
  'peach-cobbler=YummyCookies; Path=/; Secure; SameSite=Lax',
  'cherry-almond=YummyCookies; Path=/; Max-Age=14400',
  'hazelnut=YummyCookies; Path=/; HttpOnly; SameSite=Strict',
  'pumpkin-spice=YummyCookies; Path=/; Max-Age=18000',
  'caramel-macchiato=YummyCookies; Path=/;',
  'butter-pecan=YummyCookies; Path=/; Max-Age=432000',
  'coconut-macaroon=YummyCookies; Path=/; HttpOnly; Secure',
  'toffee-crunch=YummyCookies; Path=/; Max-Age=10800',
  'maple-pecan=YummyCookies; Path=/; SameSite=Lax',
  'apple-cinnamon=YummyCookies; Path=/; Secure',
  'dark-chocolate-mint=YummyCookies; Path=/; Max-Age=21600',
  'almond-joy=YummyCookies; Path=/; Max-Age=36000',
  'raspberry-linzer=YummyCookies; Path=/; HttpOnly',
  'pistachio=YummyCookies; Path=/; Secure; SameSite=Strict',
  'bacon-maple=YummyCookies; Path=/; Max-Age=10800',
  'peanut-butter-choc-chip=YummyCookies; Path=/; HttpOnly; SameSite=Lax',
  'brownie-batter=YummyCookies; Path=/;',
  's-mores=YummyCookies; Path=/; Max-Age=86400',
  'mon-made-cookie=YummyCookies; Path=/; Secure; SameSite=Strict',
  'dad-made-cookie=YummyCookies; Path=/; Secure; SameSite=Strict',
  'cookie-clicker-cookie=YummyCookies; Path=/; Secure',
  'butterscotch=YummyCookies; Path=/; Max-Age=7200',
  'cinnamon-roll=YummyCookies; Path=/;',
  'peanut-butter-cup=YummyCookies; Path=/; SameSite=Lax',
  'orange-cranberry=YummyCookies; Path=/; Max-Age=14400',
  'chocolate-covered-pretzel=YummyCookies; Path=/; Secure; SameSite=Strict',
  'maple-bacon=YummyCookies; Path=/; Max-Age=18000',
  'birthday-cake=YummyCookies; Path=/;',
  'cherry-pie=YummyCookies; Path=/; HttpOnly',
  'mocha=YummyCookies; Path=/; Max-Age=36000',
  'sugar-cookie=YummyCookies; Path=/; Secure',
  'raspberry-chocolate=YummyCookies; Path=/; Max-Age=21600',
  'pecan-pie=YummyCookies; Path=/;',
  'espresso=YummyCookies; Path=/; SameSite=Lax',
  'toasted-coconut=YummyCookies; Path=/; Max-Age=432000',
  'triple-chocolate=YummyCookies; Path=/; Secure; SameSite=Strict',
  'yuumy-cookie=YummyCookies; Path=/; HttpOnly',
];
